var questions = [
    'Watched mickey mouse on a saturday morning',
    'Played purple place',
    'Cheated on someone',
    'Mummy se maar khai hai',
    'Went camping',
    'Slept for more than 12 hours  continuously (full kumbh karan types)',
    'Studied wrong subject for the test ',
    'Ate or drank something while fasting',
    'Lied about my age',
    'Danced in a baraat, preferably naagin dance',
    'Attended a wedding out of your home town',
    'Regretted not eating an extra plate of that one dish in a wedding',
    'Pretended to have a non-existent best friend in school',
    'Pretended to be sick to skip school assembly',
    'Watched Harry Potter ',
    'Pretended to be sick to skip school ',
    'Tried learning something online and failed (humari sympathy aapke saath hai)',
    'Threw away a medicine mummy gave to eat ',
    'Did horse riding',
    'Told my crush ke mai tennu kinna pyaar kidda si',
    'Flirted with a stranger',
    'Danced in rain',
    'Forgot umbrella aur baarish ho gyi hehe',
    'Made maggi at 2am with your siblings or alone ',
    'Pool me dubki lagai',
    'Binge watched an entire season or more in a single day of a web series',
    'Wished ke avengers real hote ',
    'Watched phir hera pheri',
    'Ate doosro ka tiffin, mostly before recess',
    'Been hospitalized for something other than giving birth or being born.',
    'Played a musical instrument',
    'Traveled to a foreign country',
    'Sang in public',
    'Rejected someone and regretted',
    'Said i love you without meaning it',
    'Watched Takeshi\'s castle',
    'Read a whole book in a day (100 pages+)',
    'Tried learning a new language',
    '2 din lagatar dosto ke saath ghumne gye',
    'Went on a solo trip',
    'Told someone ke bas 5 minute me pahunch rahe while still deciding what to wear',
    'Had a sleepover at friend\'s house',
    'Watched 5 minute crafts',
    'Tried runaway aurora trend',
    'Watched reels till the deadly message, 100% of data used, showed up',
    'Jyada hi khaana khake got food poisoning',
    'Got sick on school bus',
    'Went on a week long trip',
    'Broken up with someone',
    'Ate something videshi with a desi twist or vice versa',
    'Went on a only friends trip',
    'Swimmed',
    'Went on a rally',
    'Made a fake ID on a social media',
    'Skip your turn man, chalta hai',
    'Went bunjee jumping',
    'Did proper dance with choreography',
    'Took part in a play/skit',
    'Ate slate pencil (aur mummy ko pata chalne pe maar khai)'
]



function newQuestion(){
    var randomNum = Math.floor((Math.random()) * (questions.length));
    document.getElementById('questionDisplay').innerHTML = questions[randomNum];
}